# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(831, 622)
        dialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.pushButton_3 = QtWidgets.QPushButton(dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 50, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 300, 81, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 300, 141, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(200, 50, 113, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(670, 50, 101, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(20, 50, 75, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 560, 101, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 430, 121, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(170, 430, 75, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(430, 170, 101, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(210, 170, 101, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 300, 75, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(540, 50, 121, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(110, 170, 91, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(20, 170, 81, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(430, 50, 101, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton = QtWidgets.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(210, 300, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(320, 170, 101, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 50, 81, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(dialog)
        self.line.setGeometry(QtCore.QRect(20, 30, 771, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(dialog)
        self.line_2.setGeometry(QtCore.QRect(30, 150, 511, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 135, 61, 21))
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(dialog)
        self.line_3.setGeometry(QtCore.QRect(30, 270, 431, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 61, 16))
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(dialog)
        self.line_4.setGeometry(QtCore.QRect(30, 400, 221, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 385, 51, 21))
        self.label_4.setObjectName("label_4")
        self.line_5 = QtWidgets.QFrame(dialog)
        self.line_5.setGeometry(QtCore.QRect(30, 530, 371, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_5 = QtWidgets.QLabel(dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 515, 61, 21))
        self.label_5.setObjectName("label_5")
        self.pushButton_20 = QtWidgets.QPushButton(dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(150, 560, 101, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(260, 560, 101, 31))
        self.pushButton_21.setObjectName("pushButton_21")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Resolution Buster 1.0"))
        self.pushButton_3.setText(_translate("dialog", "PC reload/F12"))
        self.pushButton_4.setText(_translate("dialog", "Printer Setup"))
        self.pushButton_5.setText(_translate("dialog", "Printer Service Template"))
        self.pushButton_7.setText(_translate("dialog", "Inter/Intranet Setting"))
        self.pushButton_8.setText(_translate("dialog", "Profile Reset"))
        self.pushButton_9.setText(_translate("dialog", "Slow PC"))
        self.pushButton_10.setText(_translate("dialog", "Write Off"))
        self.pushButton_11.setText(_translate("dialog", "Faulty/Slow  Network"))
        self.pushButton_12.setText(_translate("dialog", "3g Cards"))
        self.pushButton_13.setText(_translate("dialog", "Enterprise Vault"))
        self.pushButton_14.setText(_translate("dialog", "MS Office Error"))
        self.pushButton_15.setText(_translate("dialog", "Printer Faulty"))
        self.pushButton_16.setText(_translate("dialog", "Security Database"))
        self.pushButton_17.setText(_translate("dialog", "Skype/Lync"))
        self.pushButton_18.setText(_translate("dialog", "Sap GuiPortal"))
        self.pushButton_19.setText(_translate("dialog", "Logon Issues"))
        self.pushButton.setText(_translate("dialog", "Scanning Fix"))
        self.pushButton_6.setText(_translate("dialog", "Sharepoint Issues"))
        self.pushButton_2.setText(_translate("dialog", "New Pc Setup"))
        self.label.setText(_translate("dialog", "Computers"))
        self.label_2.setText(_translate("dialog", "Applications"))
        self.label_3.setText(_translate("dialog", "Printers"))
        self.label_4.setText(_translate("dialog", "Network"))
        self.label_5.setText(_translate("dialog", "SLC"))
        self.pushButton_20.setText(_translate("dialog", "Booked @ SLC"))
        self.pushButton_21.setText(_translate("dialog", "Collected @ SLC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())

